config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  post '/search', to: 'home#search'
  get '/search', to: redirect('/')
  post '/trello', to: 'home#trello'
  get '/trello', to: redirect('/')
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @board = Trello::Board.find(ENV['BOARD_ID'])
    @movie_list = Trello::List.find(ENV['TO_WATCH_LIST_ID'])
    @movie_cards = @movie_list.cards
  end

  def search
    Tmdb::Api.key(ENV['TMDB_KEY'])
    search = params[:search]
    @search_term = search
    @type = params[:media_type]
    if search != ""
      if @type == "movie"
        @results = Tmdb::Movie.find(search)
      elsif @type == "tv"
        @results = Tmdb::TV.find(search)
      else
        flash[:alert] = "You must choose Movie or TV."
        redirect_to root_path
      end
    else
      flash[:alert] = "You must enter a search term."
      redirect_to root_path
    end
  end

  def trello
    if params[:button_name] == "currently_watching"
      Trello::Card.create(name: params[:result_title], list_id: ENV['WATCHING_LIST_ID'])
      flash[:alert] = "#{params[:result_title]} added to Currently Watching!"
      redirect_to root_path
    elsif params[:button_name] == "to_watch"
      Trello::Card.create(name: params[:result_title], list_id: ENV['TO_WATCH_LIST_ID'])
      flash[:alert] = "#{params[:result_title]} added to To Watch!"
      redirect_to root_path
    elsif params[:button_name] == "watched"
      Trello::Card.create(name: params[:result_title], list_id: ENV['WATCHED_LIST_ID'])
      flash[:alert] = "#{params[:result_title]} added to Watched!"
      redirect_to root_path
    else
      flash[:alert] = "#{params[:result_title]} could not be added, please try again and tell Sean you broke his app."
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<section>
  <%= form_tag('/search') do %>
    <section>
      <%= search_field_tag 'search', nil, placeholder: "Search" %>
    </section>
    <section>
      <section>
        <label>
          <%= radio_button_tag 'media_type', 'movie' %>
          Movie
        </label>
      </section>
      <section>
        <label>
          <%= radio_button_tag 'media_type', 'tv' %>
          TV
        </label>
      </section>
    </section>
    <section>
      <%= submit_tag "Search" %>
    </section>
  <% end %>
</section>

app/views/home/search.html.erb
<section>
  <h3>Results for: "<%= @search_term %>"</h3>
</section>
<section>
  <ul>
    <% for result in @results do %>
      <% if result.poster_path %>
      <% if @type == "movie" %>
        <% @title = result.title %>
      <% else %>
        <% @title = result.name %>
      <% end %>
        <li>
          <div class="img-result">
            <%= image_tag "http://image.tmdb.org/t/p/original#{result.poster_path}" %><br>
            <div class="hover">
              <div class="hover-links">
                <%= button_to "Currently Watching", trello_path, params: { button_name: "currently_watching", result_title: @title }, data: { confirm: "Add this to the Currently Watching list on Trello?" } %>
                <%= button_to "Watch Later", trello_path, params: { button_name: "to_watch", result_title: @title }, data: { confirm: "Add this to the Watch Later list on Trello?" } %>
                <%= button_to "Already Watched", trello_path, params: { button_name: "watched", result_title: @title }, data: { confirm: "Add this to the Already Watched list on Trello?" } %>
              </div>
            </div>
            <p><%= @title %></p>
          </div>
        </li>
      <% end %>
    <% end %>
  </ul>
</section>
<footer>
  <h4><%= link_to "Search Again", root_url %></h4>
</footer>

<script>
$(document).ready(function(){
  $(".img-result").mouseover(function() {
    $(this).children(".hover").show();
  });
  $(".img-result").mouseout(function() {
    $(this).children(".hover").hide();
  });
});
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Now Showing</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header>
    <a href="/"><h1 id="title" class="title h1">NOW SHOWING</h1></a>
  </header>
  <% flash.each do |name, msg| %>
    <section><%= content_tag :section, msg %></section>
  <% end %>
  <%= yield %>
</body>
</html>